modLoader = "javafml"
loaderVersion = "[36,)"
license = "All Rights Reserved unless stated otherwise. Distribution permission is given to FeedTheBeast and CurseForge for use in modpacks"
[[mods]]
modId = "jags"
version = "${version}"
displayName = "JAGS"
description = "adds a grass seed"